# fly.toml app configuration file generated for switchr-timeline-handler on 2025-04-19T12:07:27+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'switchr-timeline-handler'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
